### PR TITLE
Added AppVeyor integration

### PR DESCRIPTION
**Pull request by 304NotModified**
Added AppVeyor integration, free for open source projects.

AppVeyor is a build server in the cloud and builds and runs unit tests in every PR. Then you're sure that PR's wont break the build or unit tests. Also you can publish to NuGet.org with a few clicks. 

Now only building `YAXLib.2013.sln`. 

How to set-up:
1. login to AppVeyor (free), with GitHub account or by creating an AppVeyor account
2. press "new project"
3. hover project, press "add"

PS: in a later phase we can added code coverage (free, also cloud service), if you like.

### CODE REVIEW

**Comment by sinairv** [comment]
I've already been using AppVeyor for CI without the `.yml` file, but not for releasing the nuget (since I'm using a key to sign the assemblies). Probably using the `.yml` file to store settings is a better way of doing this.

**Comment by 304NotModified** [comment]
I think it would be nice to:

- Add a build badge 
- enable pr building by appveyor 

So it's more clear that it compiles and you are sure PRs won't break your build / tests

**Comment by 304NotModified** [comment]
You were thinking the same regarding  the appveyor badge! Nice!

**Comment by sinairv** [comment]
It seems that the build on pull requests has been enabled by default through the web hook. No action needed.

**Pull request merged**
